class dofus.DofusLoaderLogger
{
   function DofusLoaderLogger()
   {
      this.initTexts();
   }
   function initTexts()
   {
      this["\x18\x12\x16"] = new Object();
      this["\x18\x12\x16"].STARTING = {fr:"Initialisation de <font color=\"#FF9911\">DOFUS RETRO</font>...",en:"Initializing <font color=\"#FF9911\">DOFUS RETRO</font>...",es:"Inicializando <font color=\"#FF9911\">DOFUS RETRO</font>...",de:"Initialisierung von <font color=\"#FF9911\">DOFUS RETRO</font> im Gange...",pt:"Inicializando <font color=\"#FF9911\">DOFUS RETRO</font>...",nl:"<font color=\"#FF9911\">DOFUS RETRO</font> initialiseren...",it:"Inizializzazione <font color=\"#FF9911\">DOFUS RETRO</font>..."};
      this["\x18\x12\x16"].SERVER = {fr:"Serveur",en:"\x1a\x14\x05",es:"Servidor",de:"\x1a\x14\x05",pt:"Servidor",nl:"\x1a\x14\x05",it:"\x1a\x14\x05"};
      this["\x18\x12\x16"].CONFIGURATION = {fr:"Configuration",en:"Configuration",es:"Configuración",de:"Konfiguration",pt:"Configuração",nl:"Configuratie",it:"Configurazione"};
      this["\x18\x12\x16"].NEXT = {fr:"Continuer",en:"Next",es:"Siguiente",de:"Weiter",pt:"Próximo",nl:"Volgende",it:"Continuare"};
      this["\x18\x12\x16"].INIT_END = {fr:"Initialisation terminée",en:"Initialization completed",es:"Inicialización terminada",de:"Initialisierung beendet",pt:"Inicialização completada",nl:"Initialiseren voltooid",it:"Inizializzazzione terminata"};
      this["\x18\x12\x16"].VALID = {fr:"OK",en:"OK",es:"OK",de:"OK",pt:"OK",nl:"OK",it:"OK"};
      this["\x18\x12\x16"].CLEAR_CACHE = {fr:"Vider le cache",en:"Empty cache memory",es:"Vacía el caché",de:"Den Cache leeren",pt:"Esvaziar memória cache",nl:"Cache geheugen legen",it:"Svuotare la cache"};
      this["\x18\x12\x16"].COPY_LOGS = {fr:"Copier les logs",en:"Copy logs",es:"Copiar logs",de:"Logs kopieren",pt:"Copiar logs",nl:"Logs kopiëren",it:"Copiare i log"};
      this["\x18\x12\x16"].SHOW_LOGS = {fr:"Afficher les logs",en:"Display logs",es:"Mostrar logs",de:"Logs anzeigen",pt:"Exibir logs",nl:"Laat de logs zien",it:"Visualizzare i log"};
      this["\x18\x12\x16"].CONTINUE = {fr:"Continuer",en:"Continue",es:"Continuar",de:"Fortfahren",pt:"Continuar",nl:"Volgende",it:"Continuare"};
      this["\x18\x12\x16"].ERROR = {fr:"Erreur",en:"Error",es:"Error",de:"Fehler",pt:"Erro",nl:"Fout",it:"Errore"};
      this["\x18\x12\x16"].WARNING = {fr:"Attention",en:"Warning",es:"Atención",de:"Warnung",pt:"Aviso",nl:"Waarschuwing",it:"Attenzione"};
      this["\x18\x12\x16"].DEBUG_MODE = {fr:"Mode debug activé",en:"Debug mode activated",es:"Modo debug activado",de:"Debug Modus aktiviert",pt:"Modo de depuração ativado",nl:"Debug modus geactiveerd",it:"Modalità debug attiva"};
      this["\x18\x12\x16"].UNKNOWN_TYPE_NODE = {fr:"Paramètre inconnu",en:"Unknown parameter",es:"Parámetro desconocido",de:"Unbekannte Parameter",pt:"Parâmetro desconhecido",nl:"Onbekende parameter",it:"Parametro sconosciuto"};
      this["\x18\x12\x16"].LINK_HELP = {fr:"Cliquez ici pour voir les solutions",en:"Click here to see the solutions",es:"Pincha aquí para ver las soluciones",de:"Hier klicken für Lösungsvorschläge",pt:"Clique aqui para ver as soluções",nl:"Klik hier voor de oplossingen",it:"Clicca qui per vedere le soluzioni"};
      this["\x18\x12\x16"].LOADING_CONFIG_FILE = {fr:"Chargement du fichier de configuration...",en:"Configuration file downloading...",es:"Descargando el archivo de configuración",de:"Download der Konfigurationsdatei...",pt:"Baixando arquivo de configuração...",nl:"Configuratie bestand aan het downloaden...",it:"Caricamento del file di configurazione..."};
      this["\x18\x12\x16"].CONFIG_FILE_LOADED = {fr:"Fichier de configuration chargé",en:"Configuration file downloaded",es:"Archivo de configuración descargado",de:"Download der Konfigurationsdatei beendet",pt:"Arquivo de configuração baixado",nl:"Configuratie bestand gedownload",it:"File di configurazione caricato"};
      this["\x18\x12\x16"].CHOOSE_CONFIGURATION = {fr:"Choix de la configuration...",en:"Configuration choice...",es:"Elección de la configuración...",de:"Auswahl der Konfiguration...",pt:"Escolha de configuração...",nl:"Configuratie keuze...",it:"Scelta della configurazione..."};
      this["\x18\x12\x16"].LOAD_MODULES = {fr:"Chargement des modules de jeu...",en:"Game modules loading...",es:"Descargando módulos del juego...",de:"Spielmodule werden geladen...",pt:"Carregando módulos de jogo...",nl:"Spel modules aan het laden...",it:"Caricamento dei moduli di gioco..."};
      this["\x18\x12\x16"].CURRENT_CONFIG = {fr:"Configuration choisie : <b>%1</b>",en:"Chosen Configuration : <b>%1</b>",es:"Configuración elegida: <b>%1</b>",de:"Ausgewählte Konfiguration: <b>%1</b>",pt:"Configuração escolhida : <b>%1</b>",nl:"Gekozen Configuratie : <b>%1</b>",it:"Configurazione scelta : <b>%1</b>"};
      this["\x18\x12\x16"].CURRENT_SERVER = {fr:"Server de connexion choisi : <b>%1</b>",en:"Chosen Connection Server : <b>%1</b>",es:"Servidor de conexión seleccionado: <b>%1</b>",de:"Ausgewählter Einwahlserver: <b>%1</b>",pt:"Conexão com o servidor escolhida : <b>%1</b>",nl:"Gekozen Verbindings Server : <b>%1</b>",it:"Server di connessione scelto : <b>%1</b>"};
      this["\x18\x12\x16"].LOAD_LANG_FILE = {fr:"Chargement du fichier de langue...",en:"Language file downloading...",es:"Descargando el archivo de idioma...",de:"Laden der Sprachdateien im Gange...",pt:"Baixando arquivo de idioma...",nl:"Taalbestand aan het downloaden...",it:"Caricamento del file di lingua..."};
      this["\x18\x12\x16"].CURRENT_LANG_FILE_VERSION = {fr:"Version du fichier de langue en local : <b>%1</b>",en:"Local version of the language file : <b>%1</b>",es:"Versión local del archivo de idioma: <b>%1</b>",de:"Lokale Version der Sprachdatei: <b>%1</b>",pt:"Versão locais do arquivo de idioma : <b>%1</b>",nl:"Locale versie van het taalbestand : <b>%1</b>",it:"Versione del file di lingua in rete locale : <b>%1</b>"};
      this["\x18\x12\x16"].CHECK_LAST_VERSION = {fr:"Verification des mises à jour...",en:"Checking updates...",es:"Comprobando actualizaciones...",de:"Suchen nach Updates...",pt:"Verificando atualizações...",nl:"Zoeken naar updates...",it:"Verifica degli aggiornamenti..."};
      this["\x18\x12\x16"].NEW_LANG_FILE_AVAILABLE = {fr:"Mise à jour disponible, téléchargement en cours de la version <b>%1</b>",en:"Update available. Version <b>%1</b> downloading...",es:"Actualización disponible. Descargando versión <b>%1</b>...",de:"Update gefunden. Download von Version <b>%1</b> im Gange...",pt:"Atualização disponível. Baixando versão <b>%1</b>...",nl:"Update beschikbaar/ Versie <b>%1</b> aan het downloaden...",it:"Aggiornamenti disponibili, download della versione in corso <b>%1</b>..."};
      this["\x18\x12\x16"].NO_NEW_VERSION_AVAILABLE = {fr:"Aucune mise à jour disponible",en:"No update available",es:"Ninguna actualización disponible",de:"Kein Update verfügbar",pt:"Não há atualização disponível",nl:"Geen update beschikbaar",it:"Nessun aggiornamento disponibile"};
      this["\x18\x12\x16"].IMPOSSIBLE_TO_JOIN_SERVER = {fr:"Impossible de joindre le serveur <b>%1</b>",en:"Server <b>%1</b> can not be reached",es:"Imposible conectar con el servidor <b>%1</b>",de:"Server <b>%1</b> unerreichbar",pt:"Servidor <b>%1</b> não pôde ser alcançado",nl:"Server <b>%1</b> kon niet bereikt worden",it:"Non è possibile collegarsi al server <b>%1</b>"};
      this["\x18\x12\x16"].LOAD_XTRA_FILES = {fr:"Chargement des fichiers de langue supplémentaires...",en:"Additional language files downloading...",es:"Descargando archivos de idioma adicionales...",de:"Download zusätzlicher Sprachdateien im Gange...",pt:"Baixando arquivos adicionais de idioma...",nl:"Additioneel taalbestand aan het downloaden...",it:"Caricamento del file di lingua supplementari..."};
      this["\x18\x12\x16"].UPDATE_FILE = {fr:"Mise à jour du fichier <b>%1</b>...",en:"Updating file <b>%1</b>...",es:"Actualizando el archivo <b>%1</b>...",de:"Update der Datei <b>%1</b> im Gange...",pt:"Atualizando arquivo <b>%1</b>...",nl:"Bestand <b>%1</b> aan het updaten...",it:"Aggiornamento del file <b>%1</b>..."};
      this["\x18\x12\x16"].NO_FILE_IN_LOCAL = {fr:"Fichier <b>%1</b> non présent dans le dossier local <b>%2</b>",en:"File <b>%1</b> can not be found in local folder <b>%2</b>",es:"No se consiguió encontrar el archivo <b>%1</b> en la carpeta <b>%2</b>",de:"Datei <b>%1</b> gefindet sich nicht im lokalen Ordner <b>%2</b>",pt:"Arquivo <b>%1</b> não pôde ser encontrado na pasta local <b>%2</b>",nl:"Bestand <b>%1</b> kan niet in de lokale folder <b>%2</b> worden gevonden",it:"File <b>%1</b>  non presente nella cartella locale <b>%2</b>"};
      this["\x18\x12\x16"].IMPOSSIBLE_TO_DOWNLOAD_FILE = {fr:"Impossible de télécharger le fichier <b>%1</b> a partir du serveur <b>%2</b>",en:"File <b>%1</b> can not be downloaded from server <b>%2</b>",es:"Ha sido imposible descargar el archivo <b>%1</b> desde el servidor <b>%2</b>",de:"Download der Datei <b>%1</b> vom Server <b>%2</b> fehlgeschlagen",pt:"Arquivo <b>%1</b> não foi baixando do servidor <b>%2</b>",nl:"Bestand <b>%1</b> kan niet van server <b>%2</b> worden gedownload",it:"Non è possibile scaricare il file <b>%1</b> dal server <b>%2</b>"};
      this["\x18\x12\x16"].UPDATE_FINISH = {fr:"Mise à jour du fichier <b>%1</b> terminée à partir du serveur <b>%2</b>",en:"Update of file <b>%1</b> from server <b>%2</b> completed",es:"Actualización del archivo <b>%1</b> a partir del servidor <b>%2</b>terminada",de:"Update der Datei <b>%1</b> vom Server <b>%2</b> abgeschlossen",pt:"Atualização do arquivo <b>%1</b> do servidor <b>%2</b> completada",nl:"Update van het bestand <b>%1</b> van server <b>%2</b> is voltooid",it:"Aggiornamento del file <b>%1</b>dal server terminato <b>%2</b>"};
      this["\x18\x12\x16"].MODULE_LOADED = {fr:"Module <b>%1</b> chargé",en:"Module <b>%1</b> downloaded",es:"Módulo <b>%1</b> descargado",de:"Download von Modul <b>%1</b> abgeschlossen",pt:"Módulo <b>%1</b> baixado",nl:"Module <b>%1</b> gedownload",it:"Modulo <b>%1</b> caricato"};
      this["\x18\x12\x16"].FILE_LOADED = {fr:"Chargement du fichier <b>%1</b> terminé à partir du dossier local <b>%2</b>",en:"File <b>%1</b> from local folder <b>%2</b> downloaded",es:"Archivo <b>%1</b> de la carpeta <b>%2</b> descargado",de:"Download der Datei <b>%1</b> vom lokalen Ordner <b>%2</b> abgeschlossen",pt:"Arquivo <b>%1</b> da pasta local <b>%2</b> baixado",nl:"Bestand <b>%1</b> uit de lokale folder <b>%2</b> is gedownload",it:"Caricamento del file <b>%1</b> dalla cartella locale terminato <b>%2</b>"};
      this["\x18\x12\x16"].CORRUPT_FILE = {fr:"Fichier <b>%1</b> corrompu téléchargé à partir du serveur <b>%2</b> (Taille : %3)",en:"File <b>%1</b> corrupted. Downloaded from server <b>%2</b> (Size: %3)",es:"El archivo <b>%1</b> está corrupto. Descargado desde el servidor <b>%2</b> (Tamaño: %3)",de:"Datei <b>%1</b> ist korrupt. Heruntergeladen vom Server <b>%2</b> (Größe: %3)",pt:"Arquivo <b>%1</b> corrompido. Baixado do servidor <b>%2</b> (Tamanho: %3)",nl:"Bestand <b>%1</b> is beschadigd. Download van server <b>%2</b> (Grootte: %3)",it:"File <b>%1</b> corrotto scaricato dal server <b>%2</b> (Taglia: %3)"};
      this["\x18\x12\x16"].IMPOSSIBLE_TO_GET_FILE = {fr:"Impossible de récupérer la ressource <b>%1</b>",en:"Unable to get the resource <b>%1</b>",es:"No se ha podido recuperar el recurso <b>%1</b>",de:"Ressource <b>%1</b> kann nicht abgerufen werden",pt:"Não foi possível recuperar o recurso <b>%1</b>",nl:"Kan bron <b>%1</b> niet ophalen",it:"Impossibile recuperare la risorsa <b>%1</b>"};
      this["\x18\x12\x16"].CHECKING_VERSIONS = {fr:"Vérification des versions en ligne",en:"Checking online versions",es:"Comprobación de las versiones en línea",de:"Überprüfung von Online-Versionen",pt:"Verificação das versões em linha",nl:"Online versies controleren",it:"Controllo delle versioni online"};
      this["\x17\r\x1b"] = new Object();
      var _loc2_ = new Object();
      this["\x17\r\x1b"].TOO_MANY_OCCURENCES = _loc2_;
      _loc2_.fr = "Vous ne pouvez pas lancer plus de clients DOFUS sur cet ordinateur.";
      _loc2_.en = "You can\'t start anymore DOFUS client on this computer.";
      _loc2_.es = "No puedes abrir más clientes DOFUS en este ordenador.";
      _loc2_.de = "Es kann kein weiterer DOFUS-Client auf diesem Computer gestartet werden.";
      _loc2_.pt = "Você não pode começar o cliente de DOFUS de novo neste computador.";
      _loc2_.nl = "Je kan de DOFUS client niet meer op deze computer opstarten.";
      _loc2_.it = "Non puoi lanciare più client su questo computer.";
      _loc2_.linkfr = "http://www.dofus.com";
      _loc2_.linken = "http://www.dofus.com";
      _loc2_.linkes = "http://www.dofus.com";
      _loc2_.linkde = "http://www.dofus.com";
      _loc2_.linkpt = "http://www.dofus.com";
      _loc2_ = new Object();
      this["\x17\r\x1b"].BAD_FLASH_PLAYER = _loc2_;
      _loc2_.fr = "Vous devez posséder le lecteur Flash Player version 8 ou supérieure. (Version actuelle : " + System.capabilities.version + ")";
      _loc2_.en = "You have to install the Flash Player version 8 or higher. (Actual version : " + System.capabilities.version + ")";
      _loc2_.es = "Debes instalar el reproductor Flash Player versión 8 o superior. (Versión actual: " + System.capabilities.version + ")";
      _loc2_.de = "Es wird die Version 8 oder höher des Flash Players benötigt. (Aktuelle Version: " + System.capabilities.version + ")";
      _loc2_.pt = "Você precisa instalar a versão 8 ou superior do Flash Player. (Versão atual : " + System.capabilities.version + ")";
      _loc2_.nl = "Je moet Flash Player versie 8 of hoger installeren. (Huidige versie : " + System.capabilities.version + ")";
      _loc2_.it = "Devi avere il lettore Flash Player versione 8 o avanzata (Versione attuale:" + System.capabilities.version + ")";
      _loc2_.linkfr = "http://store.adobe.com/go/getflashplayer";
      _loc2_.linken = "http://store.adobe.com/go/getflashplayer";
      _loc2_.linkes = "http://store.adobe.com/go/getflashplayer";
      _loc2_.linkde = "http://store.adobe.com/go/getflashplayer";
      _loc2_.linkpt = "http://store.adobe.com/go/getflashplayer";
      _loc2_ = new Object();
      this["\x17\r\x1b"].BAD_FLASH_SANDBOX = _loc2_;
      _loc2_.fr = "Les paramètres de sécurité actuels du lecteur Flash ne permettent pas à DOFUS de s\'executer.";
      _loc2_.en = "You must configure DOFUS as a trusted application on the Flash Player security settings.";
      _loc2_.es = "Los parámetros de seguridad actuales del reproductor Flash no permiten la ejecución de DOFUS.";
      _loc2_.de = "DOFUS muss als vertrauenswürdige Anwendung in den Sicherheitseinstellungen des Flash Players konfiguriert werden.";
      _loc2_.pt = "Você deve configurar DOFUS como uma aplicação confiável nas configurações de segurança do Flash Player.";
      _loc2_.nl = "Je zult DOFUS als een veilige aplicatie moeten instellen bij de beveiligings instellingen van je Flash Player.";
      _loc2_.it = "I parametri di sicurezza attuali del lettore Flash non permettono l\'esecuzione di DOFUS.";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=984&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=985&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=985&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=985&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=985&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].UPDATE_LANG_IMPOSSIBLE = _loc2_;
      _loc2_.fr = "Impossible de charger le fichier de langue";
      _loc2_.en = "Impossible to download the language file";
      _loc2_.es = "Descarga del archivo de idioma imposible";
      _loc2_.de = "Download der Sprachdatei nicht möglich";
      _loc2_.pt = "Impossível baixar o arquivo de idioma";
      _loc2_.nl = "Onmogelijk om dit taalbestand te downloaden";
      _loc2_.it = "Non è possibile caricare il file di lingua";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=961&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=971&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=971&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=971&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=971&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].NO_CONFIG_FILE = _loc2_;
      _loc2_.fr = "Impossible de charger le fichier de configuration";
      _loc2_.en = "Impossible to load the configuration file";
      _loc2_.es = "No se puede cargar el archivo de configuración";
      _loc2_.de = "Laden der Konfigurationsdatei nicht möglich";
      _loc2_.pt = "Impossível carregar o arquivo de configuração";
      _loc2_.nl = "Onmogelijk om het configuratie bestand te laden";
      _loc2_.it = "Non è possibile caricare il file di configurazione";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=957&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].CORRUPT_CONFIG_FILE = _loc2_;
      _loc2_.fr = "Impossible de lire le fichier de configuration";
      _loc2_.en = "Impossible to read the configuration file";
      _loc2_.es = "No es posible leer el archivo de configuración";
      _loc2_.de = "Unmöglich die Konfigurationsdatei zu lesen";
      _loc2_.pt = "Impossível ler o arquivo de configuração";
      _loc2_.nl = "Onmogelijk om het configuratie bestand te lezen";
      _loc2_.it = "Non è possibile leggere il file di configurazione";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=957&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=968&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].CHECK_LAST_VERSION_FAILED = _loc2_;
      _loc2_.fr = "Impossible de vérifier les mises à jour";
      _loc2_.en = "Impossible to check updates";
      _loc2_.es = "No es posible comprobar las actualizacones";
      _loc2_.de = "Updateprüfung nicht möglich";
      _loc2_.pt = "Impossível verificar atualizações";
      _loc2_.nl = "Onmogelijk om op updates te controleren";
      _loc2_.it = "Non è possibile verificare gli aggiornamenti";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=955&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].IMPOSSIBLE_TO_LOAD_MODULE = _loc2_;
      _loc2_.fr = "Impossible de charger le module <b>%1</b>";
      _loc2_.en = "Impossible to download the module <b>%1</b>";
      _loc2_.es = "No es posible descargar el módulo <b>%1</b>";
      _loc2_.de = "Download des Moduls  <b>%1</b> nicht möglich";
      _loc2_.pt = "Impossível baixar o módulo <b>%1</b>";
      _loc2_.nl = "Onmogelijk om module <b>%1</b> te downloaden";
      _loc2_.it = "Non è possibile caricare il modulo <b>%1</b>";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=963&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=976&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=976&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=976&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=976&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].WRITE_FAILED = _loc2_;
      _loc2_.fr = "Impossible de sauvegarder le fichier <b>%1</b> en local";
      _loc2_.en = "Impossible to save file <b>%1</b> in local";
      _loc2_.es = "No es posible guardar el archivo <b>%1</b> en local";
      _loc2_.de = "Lokales Speichern der Datei <b>%1</b> nicht möglich";
      _loc2_.pt = "Impossível salvar o arquivo <b>%1</b> localmente";
      _loc2_.nl = "Onmogelijk het bestand <b>%1</b> lokaal te bewaren";
      _loc2_.it = "Non è possibile registrare il file <b>%1</b> su rete locale";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=965&_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=973&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=973&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkde = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=973&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=973&_gid=1&languageid=1&group=dofusen";
      _loc2_ = new Object();
      this["\x17\r\x1b"].CANT_UPDATE_FILE = _loc2_;
      _loc2_.fr = "Impossible de mettre a jour le fichier <b>%1</b>";
      _loc2_.en = "Impossible to update file <b>%1</b>";
      _loc2_.es = "No es posible actualizar el archivo <b>%1</b>";
      _loc2_.de = "Update der Datei <b>%1</b> nicht möglich";
      _loc2_.pt = "Impossível atualizar o arquivo <b>%1</b>";
      _loc2_.nl = "Onmogelijk om het bestand <b>%1</b> te updaten";
      _loc2_.it = "Non è possibile aggiornare il file <b>%1</b>";
      _loc2_.linkfr = "http://support.ankama-games.com/index.php?_gid=1&languageid=2&group=dofusfr";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkes = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_.linken = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
      _loc2_.linkpt = "http://support.ankama-games.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=967&_gid=1&languageid=1&group=dofusen";
   }
   function §\x1e\x1a\x01§()
   {
      return this["\x17\r\x1b"];
   }
   function get langs()
   {
      return this["\x18\x12\x16"];
   }
}
