class dofus.DofusCore extends ank.utils.§\x1a\t\t§
{
   function DofusCore(mcRoot)
   {
      super();
      System.security.allowDomain("*");
      getURL("FSCommand:" add "trapallkeys","true");
      dofus.DofusCore._mcCore = mcRoot;
      dofus.DofusCore._cCore = this;
      _global.subtrace = trace;
   }

   static function getClip()
   {
      if(_root.CORECONTAINER == undefined)
      {
         _root.createEmptyMovieClip("CORECONTAINER",_root.getNextHighestDepth());
      }
      return _root.CORECONTAINER;
   }

   static function getInstance()
   {
      return dofus.DofusCore._cCore;
   }

   function initStart()
   {
      this.registerAllClasses();
      ank.utils.Extensions.addExtensions();
      this.addToQueue({object:this,method:this.addNodes});
   }

   function addNodes()
   {
      var _loc2_ = dofus.DofusCore.getClip();
      this._mcTMCC = _loc2_.createEmptyMovieClip("\x1b\x0f\t",_loc2_.getNextHighestDepth());
      this._mcTMCC._visible = false;
      _loc2_.attachMovie("BATTLEFIELD","BATTLEFIELD",_loc2_.getNextHighestDepth());
      _loc2_.attachMovie("GAPIMain","GAPI",_loc2_.getNextHighestDepth());
      _loc2_.attachMovie("mask","MASK",_loc2_.getNextHighestDepth());
      this.addToQueue({object:this,method:this.initApi});
   }

   function initApi()
   {
      new org.flashdevelop.utils.FlashConnect.trace("Etape 3","dofus.DofusCore::initApi","C:\\Users\\ddallinge\\Git\\client\\src\\core\\classes/dofus/DofusCore.as",102);
      _global.api = new dofus.utils.getInstance();
      _global.api.initialize();
      this.addToQueue({object:this,method:this.checkNodesAndContinue});
   }

   function checkNodesAndContinue()
   {
      if(this.checkNodes())
      {
         this.startGame();
      }
      else
      {
         this.addToQueue({object:this,method:this.checkNodesAndContinue});
      }
   }

   function checkNodes()
   {
      if(_global.api.gfx.initialize == undefined)
      {
         return false;
      }
      if(_global.api.kernel.start == undefined)
      {
         return false;
      }
      if(_global.api.ui.loadUIComponent == undefined)
      {
         return false;
      }
      return true;
   }

   function startGame()
   {
      new org.flashdevelop.utils.FlashConnect.trace("Etape 5, fin","dofus.DofusCore::startGame","C:\\Users\\ddallinge\\Git\\client\\src\\core\\classes/dofus/DofusCore.as",157);
      _global.api.kernel.start();
   }

   function forceMouseOver()
   {
      var _loc2_ = dofus.DofusCore.getClip();
      _loc2_.attachMovie("clipForceOver","_mcForceOver",1000,{_x:_loc2_._xmouse,_y:_loc2_._ymouse});
   }

   function getTemporaryContainer()
   {
      return this._mcTMCC;
   }

   function registerAllClasses()
   {
      Object.registerClass("GAPILoader",ank.gapi.controls.Loader);
      Object.registerClass("UI_AskYesNoWithString",dofus.graphics.gapi.ui.AskYesNoWithString);
      Object.registerClass("ButtonValidUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonValidDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonUnknownDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonUnknownUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMonsterDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMonsterUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonRecipeDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonRecipeUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonRightDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonRightUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonLeftDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonLeftUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ShortcutsChatReplacementPanel",dofus.graphics.gapi.controls["\x16\x19\x0b"].ShortcutsChatReplacementPanel);
      Object.registerClass("FighterEffectsReplacementPanel",dofus.graphics.gapi.controls["\x16\x19\x0b"].FighterEffectsReplacementPanel);
      Object.registerClass("UI_MakeReport",dofus.graphics.gapi.ui.MakeReport);
      Object.registerClass("UI_NewModReportAdmin",dofus.graphics.gapi.ui.nmr.NewModReportAdmin);
      Object.registerClass("UI_ModReportCategoryItem",dofus.graphics.gapi.ui.nmr.ModReportCategoryItem);
      Object.registerClass("UI_ModReportObjectItem",dofus.graphics.gapi.ui.nmr.ModReportObjectItem);
      Object.registerClass("UI_ReportPlayerToModeration",dofus.graphics.gapi.ui.ReportPlayerToModeration);
      Object.registerClass("UI_MakeMimibiote",dofus.graphics.gapi.ui.MakeMimibiote);
      Object.registerClass("UI_ChooseReward",dofus.graphics.gapi.ui.ChooseReward);
      Object.registerClass("UI_ChooseReward_TripleFramerate",dofus.graphics.gapi.ui.ChooseReward);
      Object.registerClass("UI_EditPlayer",dofus.graphics.gapi.ui.EditPlayer);
      Object.registerClass("Label",ank.gapi.controls.Label);
      Object.registerClass("ButtonNormalDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonNormalUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonToggleDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonToggleUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSimpleRectangleUpDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("Button",ank.gapi.controls.Button);
      Object.registerClass("SpellsItem",dofus.graphics.gapi.ui.spells.SpellsItem);
      Object.registerClass("GiftItem",dofus.graphics.gapi.ui.gifts.GiftItem);
      Object.registerClass("BackgroundHidder",ank.gapi.controls.BackgroundHidder);
      Object.registerClass("UI_DirectionChooser",dofus.graphics.gapi.ui.DirectionChooser);
      Object.registerClass("ButtonSimpleRectangleUpDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("UI_CardsCollectionContainerHighlight",dofus.graphics.gapi.ui["\x18\f\n"].ContainerHighlight);
      Object.registerClass("UI_CardsCollectionContainerBackground",dofus.graphics.gapi.ui["\x18\f\n"].ContainerBackground);
      Object.registerClass("ButtonMainMenuUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSpellsUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCraftUpInvert",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCraftUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMainMenuDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSpellsDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCraftDownInvert",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCraftDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("TimelinePointer",dofus.graphics.gapi.controls["\x1b\x10\x02"].TimelinePointer);
      Object.registerClass("DeathCounter",dofus.graphics.gapi.controls.DeathCounter);
      Object.registerClass("VerticalChrono",ank.gapi.controls.VerticalChrono);
      Object.registerClass("TimelineItem",dofus.graphics.gapi.controls["\x1b\x10\x02"].TimelineItem);
      Object.registerClass("ListInventoryViewerItemNoPrice",dofus.graphics.gapi.controls["\x18\x15\x10"].ListInventoryViewerItemNoPrice);
      Object.registerClass("BookPageIndexChapterItem",dofus.graphics.gapi.controls["\x16\x0f\x1d"].BookPageIndexChapterItem);
      Object.registerClass("MountStorageMountItem",dofus.graphics.gapi.ui["\x18\x1e\r"].MountStorageMountItem);
      Object.registerClass("ListInventoryViewerItem",dofus.graphics.gapi.controls["\x18\x15\x10"].ListInventoryViewerItem);
      Object.registerClass("Window",ank.gapi.controls.Window);
      Object.registerClass("ComboBoxNormal",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonComboBoxDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonComboBoxUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ComboBox",ank.gapi.controls.ComboBox);
      Object.registerClass("ListInventoryViewer",dofus.graphics.gapi.controls.ListInventoryViewer);
      Object.registerClass("TextArea",ank.gapi.controls.TextArea);
      Object.registerClass("SelectableRow",ank.gapi.controls.list.SelectableRow);
      Object.registerClass("DefaultCellRenderer",ank.gapi.controls.list.DefaultCellRenderer);
      Object.registerClass("List",ank.gapi.controls.List);
      Object.registerClass("ProgressBar",ank.gapi.controls.ProgressBar);
      Object.registerClass("ItemViewer",dofus.graphics.gapi.controls.ItemViewer);
      Object.registerClass("ItemViewerLite",dofus.graphics.gapi.controls.ItemViewer);
      Object.registerClass("ItemViewerBigLite",dofus.graphics.gapi.controls.ItemViewer);
      Object.registerClass("ItemViewerBigDescription",dofus.graphics.gapi.controls.ItemViewer);
      Object.registerClass("ItemViewerEffects",dofus.graphics.gapi.controls.ItemViewer);
      Object.registerClass("ChooseItemSkin",dofus.graphics.gapi.controls.ChooseItemSkin);
      Object.registerClass("PlayerWeight",dofus.graphics.gapi.controls.PlayerWeight);
      Object.registerClass("UI_PlayerShopModifier",dofus.graphics.gapi.ui.PlayerShopModifier);
      Object.registerClass("UI_TaxCollectorStorage",dofus.graphics.gapi.ui.TaxCollectorStorage);
      Object.registerClass("UI_PlayerShop",dofus.graphics.gapi.ui.PlayerShop);
      Object.registerClass("UI_NpcShop",dofus.graphics.gapi.ui.NpcShop);
      Object.registerClass("DefaultBackground",ank.gapi.controls["\x16\x1d\x1a"].DefaultBackground);
      Object.registerClass("DefaultHighlight",ank.gapi.controls["\x16\x1d\x1a"].DefaultHighlight);
      Object.registerClass("Container",ank.gapi.controls.Container);
      Object.registerClass("StylizedRectangle",ank.gapi.controls.StylizedRectangle);
      Object.registerClass("ContainerGrid",ank.gapi.controls.ContainerGrid);
      Object.registerClass("UI_Inventory",dofus.graphics.gapi.ui.Inventory);
      Object.registerClass("UI_Inventory_TripleFramerate",dofus.graphics.gapi.ui.Inventory);
      Object.registerClass("Timeline",dofus.graphics.gapi.controls.Timeline);
      Object.registerClass("UI_Timeline",dofus.graphics.gapi.ui.Timeline);
      Object.registerClass("UI_ChallengeMenu",dofus.graphics.gapi.ui.ChallengeMenu);
      Object.registerClass("UI_StatsJobContainerHighlight",dofus.graphics.gapi.ui["\x18\f\n"].ContainerHighlight);
      Object.registerClass("UI_InventoryContainerHighlight",dofus.graphics.gapi.ui["\x18\f\n"].ContainerHighlight);
      Object.registerClass("UI_InventoryContainerHighlight_TripleFramerate",dofus.graphics.gapi.ui["\x18\f\n"].ContainerHighlight);
      Object.registerClass("UI_ForgemagusContainerHighlight",dofus.graphics.gapi.ui["\x18\f\n"].ContainerHighlight);
      Object.registerClass("UI_StatsJobContainerBackground2",dofus.graphics.gapi.ui["\x18\f\n"].ContainerBackground);
      Object.registerClass("UI_StatsJobContainerBackground",dofus.graphics.gapi.ui["\x18\f\n"].ContainerBackground);
      Object.registerClass("UI_InventoryContainerBackground",dofus.graphics.gapi.ui["\x18\f\n"].ContainerBackground);
      Object.registerClass("UI_ForgemagusContainerBackground",dofus.graphics.gapi.ui["\x18\f\n"].ContainerBackground);
      Object.registerClass("UI_PopupQuantity",dofus.graphics.gapi.ui.PopupQuantity);
      Object.registerClass("UI_PopupQuantityWithDescription",dofus.graphics.gapi.ui.PopupQuantityWithDescription);
      Object.registerClass("UI_PopupHexa",dofus.graphics.gapi.ui.PopupHexa);
      Object.registerClass("UI_PopupText",dofus.graphics.gapi.ui.PopupText);
      Object.registerClass("UI_StringCourse",dofus.graphics.gapi.ui.StringCourse);
      Object.registerClass("UI_StringCourse_TripleFramerate",dofus.graphics.gapi.ui.StringCourse);
      Object.registerClass("TextInput",ank.gapi.controls.TextInput);
      Object.registerClass("ButtonTransparentUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("DataGrid",ank.gapi.controls.DataGrid);
      Object.registerClass("UI_Friends",dofus.graphics.gapi.ui.Friends);
      Object.registerClass("UI_FightChallenge",dofus.graphics.gapi.ui.FightChallenge);
      Object.registerClass("FightChallengeIcon",dofus.graphics.gapi.controls.FightChallengeIcon);
      Object.registerClass("FightChallengeViewer",dofus.graphics.gapi.controls.FightChallengeViewer);
      Object.registerClass("UI_SecureCraft",dofus.graphics.gapi.ui.SecureCraft);
      Object.registerClass("UI_Craft",dofus.graphics.gapi.ui.Craft);
      Object.registerClass("UI_Exchange",dofus.graphics.gapi.ui.Exchange);
      Object.registerClass("UI_AskPrivateChat",dofus.graphics.gapi.ui.AskPrivateChat);
      Object.registerClass("UI_CenterText",dofus.graphics.gapi.ui.CenterText);
      Object.registerClass("UI_CenterInfo",dofus.graphics.gapi.ui.CenterInfo);
      Object.registerClass("UI_AskCancel",dofus.graphics.gapi.ui.AskCancel);
      Object.registerClass("UI_AskLinkWarning",dofus.graphics.gapi.ui.AskLinkWarning);
      Object.registerClass("UI_AskGameBegin",dofus.graphics.gapi.ui.AskGameBegin);
      Object.registerClass("UI_AskGameBegin_TripleFramerate",dofus.graphics.gapi.ui.AskGameBegin);
      Object.registerClass("UI_AskYesNo",dofus.graphics.gapi.ui.AskYesNo);
      Object.registerClass("UI_AskYesNoIgnore",dofus.graphics.gapi.ui.AskYesNoIgnore);
      Object.registerClass("UI_AskCustomShortcut",dofus.graphics.gapi.ui.AskCustomShortcut);
      Object.registerClass("UI_ChooseNickName",dofus.graphics.gapi.ui.ChooseNickName);
      Object.registerClass("UI_AskSecretAnswer",dofus.graphics.gapi.ui.AskSecretAnswer);
      Object.registerClass("UI_AskAlertServer",dofus.graphics.gapi.ui.AskAlertServer);
      Object.registerClass("UI_AskOk",dofus.graphics.gapi.ui.AskOk);
      Object.registerClass("UI_AskOkWait",dofus.graphics.gapi.ui.AskOkWait);
      Object.registerClass("UI_Login",dofus.graphics.gapi.ui.Login);
      Object.registerClass("UI_Login_TripleFramerate",dofus.graphics.gapi.ui.Login);
      Object.registerClass("UI_GameOver",dofus.graphics.gapi.ui.GameOver);
      Object.registerClass("UI_ItemViewer",dofus.graphics.gapi.ui.ItemViewer);
      Object.registerClass("UI_ChooseItemSkin",dofus.graphics.gapi.ui.ChooseItemSkin);
      Object.registerClass("MountViewer",dofus.graphics.gapi.controls.MountViewer);
      Object.registerClass("UI_MountViewer",dofus.graphics.gapi.ui.MountViewer);
      Object.registerClass("UI_Mount",dofus.graphics.gapi.ui.Mount);
      Object.registerClass("UI_Temporis",dofus.graphics.gapi.ui.Temporis);
      Object.registerClass("UI_SpellsCollection",dofus.graphics.gapi.ui.SpellsCollection);
      Object.registerClass("UI_SpellsCollection_TripleFrameRate",dofus.graphics.gapi.ui.SpellsCollection);
      Object.registerClass("SpellUnwrap",dofus.graphics.gapi.ui.spellscollection.SpellUnwrap);
      Object.registerClass("SpellUnwrap_TripleFramerate",dofus.graphics.gapi.ui.spellscollection.SpellUnwrap);
      Object.registerClass("SpellsCollectionItem",dofus.graphics.gapi.ui.spellscollection.SpellsCollectionItem);
      Object.registerClass("Temporis2TowerStepItem",dofus.graphics.gapi.ui.temporis2.Temporis2TowerStepItem);
      Object.registerClass("CircleBar",ank.gapi.controls.CircleBar);
      Object.registerClass("UI_StatsJob",dofus.graphics.gapi.ui.StatsJob);
      Object.registerClass("AlignmentViewer",dofus.graphics.gapi.controls.AlignmentViewer);
      Object.registerClass("JobViewer",dofus.graphics.gapi.controls.JobViewer);
      Object.registerClass("StatsViewer",dofus.graphics.gapi.controls.StatsViewer);
      Object.registerClass("VolumeSlider",ank.gapi.controls.VolumeSlider);
      Object.registerClass("JobOptionsViewer",dofus.graphics.gapi.controls.JobOptionsViewer);
      Object.registerClass("CraftViewer",dofus.graphics.gapi.controls.CraftViewer);
      Object.registerClass("QuestionViewerAnswerItem",dofus.graphics.gapi.controls["\x1a\b\x1c"].QuestionViewerAnswerItem);
      Object.registerClass("GuildBoostsViewerSpell",dofus.graphics.gapi.controls["\x18\x03\x1d"].GuildBoostsViewerSpell);
      Object.registerClass("TaxCollectorsViewerItem",dofus.graphics.gapi.controls["\x1b\x0e\x07"].TaxCollectorsViewerItem);
      Object.registerClass("AlignmentViewerTreeItem",dofus.graphics.gapi.controls["\x16\x03\x01"].AlignmentViewerTreeItem);
      Object.registerClass("ChooseServerListItem",dofus.graphics.gapi.ui["\x16\x1b\x07"].ChooseServerListItem);
      Object.registerClass("UI_JoinFriend",dofus.graphics.gapi.ui.JoinFriend);
      Object.registerClass("UI_JoinFriend_TripleFramerate",dofus.graphics.gapi.ui.JoinFriend);
      Object.registerClass("CraferListItem",dofus.graphics.gapi.ui["\x17\x01\x17"]["\x17\x01\x18"]);
      Object.registerClass("MountParksViewerItem",dofus.graphics.gapi.controls["\x18\x04\x06"].MountParksViewerItem);
      Object.registerClass("GuildMembersViewerMember",dofus.graphics.gapi.controls["\x18\x04\x05"].GuildMembersViewerMember);
      Object.registerClass("UI_MemberRightItem",dofus.graphics.gapi.controls["\x18\x04\x05"].MemberRightItem);
      Object.registerClass("UI_GameResultPlayer",dofus.graphics.gapi.ui["\x17\x13\x07"]["\x17\x13\b"]);
      Object.registerClass("UI_GameResultPlayerLight",dofus.graphics.gapi.ui["\x17\x13\x07"].GameResultPlayerLight);
      Object.registerClass("UI_GameResultPlayerPVP",dofus.graphics.gapi.ui["\x17\x13\x07"].GameResultPlayerPVP);
      Object.registerClass("UI_GameResultPlayerLightPVP",dofus.graphics.gapi.ui["\x17\x13\x07"].GameResultPlayerLightPVP);
      Object.registerClass("CraftViewerCraftItem",dofus.graphics.gapi.controls["\x17\x02\x02"].CraftViewerCraftItem);
      Object.registerClass("JobViewerSkillItem",dofus.graphics.gapi.controls["\x18\x11\x11"].JobViewerSkillItem);
      Object.registerClass("StatsViewerStatItem",dofus.graphics.gapi.controls["\x1b\n\x0e"].StatsViewerStatItem);
      Object.registerClass("UI_NpcDialog",dofus.graphics.gapi.ui.NpcDialog);
      Object.registerClass("UI_GameResult",dofus.graphics.gapi.ui.GameResult);
      Object.registerClass("UI_GameResultLight",dofus.graphics.gapi.ui.GameResultLight);
      Object.registerClass("QuestionViewer",dofus.graphics.gapi.controls.QuestionViewer);
      Object.registerClass("UI_GameResultTeamPVP",dofus.graphics.gapi.ui["\x17\x13\x07"]["\x17\x13\t"]);
      Object.registerClass("UI_GameResultTeamLightPVP",dofus.graphics.gapi.ui["\x17\x13\x07"].GameResultTeamLightPVP);
      Object.registerClass("UI_GameResultTeam",dofus.graphics.gapi.ui["\x17\x13\x07"].GameResultTeam);
      Object.registerClass("UI_GameResultTeamLight",dofus.graphics.gapi.ui["\x17\x13\x07"].GameResultTeamLight);
      Object.registerClass("UI_FriendsDisconnectedItem",dofus.graphics.gapi.ui["\x17\x12\x13"]["\x17\x12\x15"]);
      Object.registerClass("UI_QuestsStepRewardItem",dofus.graphics.gapi.ui["\x1a\t\x02"]["\x1a\t\x06"]);
      Object.registerClass("UI_BigStorePriceItem",dofus.graphics.gapi.ui.bigstore["\x16\f\x1d"]);
      Object.registerClass("UI_BigStorePriceItemNoBuy",dofus.graphics.gapi.ui.bigstore["\x16\f\x1d"]);
      Object.registerClass("UI_FriendsConnectedItem",dofus.graphics.gapi.ui["\x17\x12\x13"]["\x17\x12\x14"]);
      Object.registerClass("UI_KeyCode",dofus.graphics.gapi.ui.KeyCode);
      Object.registerClass("UI_HouseIndoor",dofus.graphics.gapi.ui.HouseIndoor);
      Object.registerClass("UI_ItemUtility",dofus.graphics.gapi.ui.ItemUtility);
      Object.registerClass("MountWeight",dofus.graphics.gapi.controls.MountWeight);
      Object.registerClass("GridInventoryViewer",dofus.graphics.gapi.controls.GridInventoryViewer);
      Object.registerClass("UI_Storage",dofus.graphics.gapi.ui.Storage);
      Object.registerClass("UI_Zoom",dofus.graphics.gapi.ui.Zoom);
      Object.registerClass("UI_Tutorial",dofus.graphics.gapi.ui.Tutorial);
      Object.registerClass("UI_MainMenu",dofus.graphics.gapi.ui.MainMenu);
      Object.registerClass("UI_Register",dofus.graphics.gapi.ui.Register);
      Object.registerClass("UI_Options",dofus.graphics.gapi.ui.Options);
      Object.registerClass("UI_AskMainMenu",dofus.graphics.gapi.ui.AskMainMenu);
      Object.registerClass("UI_MountAncestorsViewer",dofus.graphics.gapi.ui.MountAncestorsViewer);
      Object.registerClass("ItemSetViewer",dofus.graphics.gapi.controls.ItemSetViewer);
      Object.registerClass("LivingItemsViewer",dofus.graphics.gapi.controls.LivingItemsViewer);
      Object.registerClass("SpellFullInfosViewerItem",dofus.graphics.gapi.controls["\x1b\x06\f"].SpellFullInfosViewerItem);
      Object.registerClass("ItemViewerItem",dofus.graphics.gapi.controls["\x18\x11\x06"].ItemViewerItem);
      Object.registerClass("ButtonMuteSoundsDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMuteMusicDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMuteSoundsUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMuteMusicUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("UI_FightOptionButtons",dofus.graphics.gapi.ui.FightOptionButtons);
      Object.registerClass("ChatArea",ank.gapi.controls.ChatArea);
      Object.registerClass("Smileys",dofus.graphics.gapi.controls.Smileys);
      Object.registerClass("Chat",dofus.graphics.gapi.controls.Chat);
      Object.registerClass("ChatFilters",dofus.graphics.gapi.controls.ChatFilters);
      Object.registerClass("CircleChrono",ank.gapi.controls.CircleChrono);
      Object.registerClass("ActionPointsViewer",dofus.graphics.gapi.controls.PointsViewer);
      Object.registerClass("Heart",dofus.graphics.gapi.controls.Heart);
      Object.registerClass("UI_Banner",dofus.graphics.gapi.ui.Banner);
      Object.registerClass("ButtonBannerRoundDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonBannerRoundUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonBannerRoundInSearchDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonBannerRoundInSearchUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonBannerRoundWaitResponseDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonBannerRoundWaitResponseUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonBannerRoundWaitResponseUp_TripleFramerate",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonRadioUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonRadioDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCheckDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCheckUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("SpellBoostViewer",dofus.graphics.gapi.controls.SpellBoostViewer);
      Object.registerClass("SpellInfosViewer",dofus.graphics.gapi.controls.SpellInfosViewer);
      Object.registerClass("UI_Spells",dofus.graphics.gapi.ui.Spells);
      Object.registerClass("UI_MountParkSale",dofus.graphics.gapi.ui.MountParkSale);
      Object.registerClass("UI_HouseSale",dofus.graphics.gapi.ui.HouseSale);
      Object.registerClass("ArtworkRotationItem",dofus.graphics.gapi.controls["\x16\x05\x0f"].ArtworkRotationItem);
      Object.registerClass("ArtworkRotation",dofus.graphics.gapi.controls.ArtworkRotation);
      Object.registerClass("UI_CreateCharacter",dofus.graphics.gapi.ui.CreateCharacter);
      Object.registerClass("ChooseCharacterSprite",dofus.graphics.gapi.controls.ChooseCharacterSprite);
      Object.registerClass("UI_ChooseCharacter",dofus.graphics.gapi.ui.ChooseCharacter);
      Object.registerClass("UI_CharactersMigration",dofus.graphics.gapi.ui.CharactersMigration);
      Object.registerClass("UI_CharactersMigrationItem",dofus.graphics.gapi.ui["\x16\x19\n"].CharactersMigrationItem);
      Object.registerClass("UI_Gifts",dofus.graphics.gapi.ui.Gifts);
      Object.registerClass("UI_ServerList",dofus.graphics.gapi.ui.ServerList);
      Object.registerClass("ChooseServerSprite",dofus.graphics.gapi.controls.ChooseServerSprite);
      Object.registerClass("UI_ChooseServer",dofus.graphics.gapi.ui.ChooseServer);
      Object.registerClass("ButtonDecorationDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("UI_PlayerInfos",dofus.graphics.gapi.ui.PlayerInfos);
      Object.registerClass("UI_PlayerInfosEffectsItem",dofus.graphics.gapi.ui["\x1a\x05\x11"]["\x1a\x05\x12"]);
      Object.registerClass("UI_ShortcutsChatReplacementPanelEffectsItem",dofus.graphics.gapi.ui["\x1a\x05\x11"]["\x1a\x05\x12"]);
      Object.registerClass("UI_WaitingQueue",dofus.graphics.gapi.ui.WaitingQueue);
      Object.registerClass("UI_WaitingMessage",dofus.graphics.gapi.ui.WaitingMessage);
      Object.registerClass("UI_Waiting",dofus.graphics.gapi.ui.Waiting);
      Object.registerClass("UI_Waiting_TripleFramerate",dofus.graphics.gapi.ui.Waiting);
      Object.registerClass("UI_DocumentParchment",dofus.graphics.gapi.ui.DocumentParchment);
      Object.registerClass("UI_DocumentBook",dofus.graphics.gapi.ui.DocumentBook);
      Object.registerClass("UI_Cinematic",dofus.graphics.gapi.ui.Cinematic);
      Object.registerClass("UI_MapInfos",dofus.graphics.gapi.ui.MapInfos);
      Object.registerClass("ClassInfosViewer",dofus.graphics.gapi.controls.ClassInfosViewer);
      Object.registerClass("ColorPicker",ank.gapi.controls.ColorPicker);
      Object.registerClass("ClassCustomize",dofus.graphics.gapi.controls.ClassCustomize);
      Object.registerClass("ButtonWomanUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonWomanDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonManDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonManUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonArrowDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonArrowUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonColorDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonColorUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCrossDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCrossUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCloseDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonEjectDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMaximizeDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMinimizeDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMoinsDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonPlusDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonCloseUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonEjectUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMaximizeUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMinimizeUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSitUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSitDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonMoinsUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonPlusUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("BannerSpriteInfos",dofus.graphics.gapi.controls.BannerSpriteInfos);
      Object.registerClass("ButtonTabDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonTabUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonTransparentUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("SpouseViewer",dofus.graphics.gapi.controls.SpouseViewer);
      Object.registerClass("SpellFullInfosViewer",dofus.graphics.gapi.controls.SpellFullInfosViewer);
      Object.registerClass("UI_SpellInfos",dofus.graphics.gapi.ui.SpellInfos);
      Object.registerClass("MapNavigator",ank.gapi.controls.MapNavigator);
      Object.registerClass("UI_MapExplorer",dofus.graphics.gapi.ui.MapExplorer);
      Object.registerClass("BookPageText",dofus.graphics.gapi.controls.BookPageText);
      Object.registerClass("BookPageIndex",dofus.graphics.gapi.controls.BookPageIndex);
      Object.registerClass("BookPageTitle",dofus.graphics.gapi.controls.BookPageTitle);
      Object.registerClass("ButtonArrowCornerDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonArrowCornerUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("Emblem",dofus.graphics.gapi.controls.Emblem);
      Object.registerClass("UI_Guild",dofus.graphics.gapi.ui.Guild);
      Object.registerClass("UI_CreateGuild",dofus.graphics.gapi.ui.CreateGuild);
      Object.registerClass("GuildMountParkViewer",dofus.graphics.gapi.controls.GuildMountParkViewer);
      Object.registerClass("TaxCollectorsViewer",dofus.graphics.gapi.controls.TaxCollectorsViewer);
      Object.registerClass("GuildBoostsViewer",dofus.graphics.gapi.controls.GuildBoostsViewer);
      Object.registerClass("GuildMembersViewer",dofus.graphics.gapi.controls.GuildMembersViewer);
      Object.registerClass("GuildInformationsViewer",dofus.graphics.gapi.controls.GuildInformationsViewer);
      Object.registerClass("Temporis_Tower",dofus.graphics.gapi.controls.temporis.TemporisTower);
      Object.registerClass("Temporis_General",dofus.graphics.gapi.controls.temporis.TemporisGeneral);
      Object.registerClass("Temporis_Rules",dofus.graphics.gapi.controls.temporis.TemporisRules);
      Object.registerClass("UI_CrafterCard",dofus.graphics.gapi.ui.CrafterCard);
      Object.registerClass("UI_GuildMemberInfos",dofus.graphics.gapi.ui.GuildMemberInfos);
      Object.registerClass("ButtonSquareUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonFlatRoundLeft",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSquareDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonJoinTaxCollectorDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonJoinTaxCollectorUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("TaxCollectorViewerPlayer",dofus.graphics.gapi.controls["\x1b\x0e\x07"]["\x1b\x0e\b"]);
      Object.registerClass("UI_Subway",dofus.graphics.gapi.ui.Subway);
      Object.registerClass("UI_MonsterAndLookSelector",dofus.graphics.gapi.ui.MonsterAndLookSelector);
      Object.registerClass("UI_ItemSelector",dofus.graphics.gapi.ui.ItemSelector);
      Object.registerClass("UI_Waypoints",dofus.graphics.gapi.ui.Waypoints);
      Object.registerClass("UI_ShortcutsItem",dofus.graphics.gapi.ui["\x1a\x1c\x10"]["\x1a\x1c\x11"]);
      Object.registerClass("UI_SubwayItem",dofus.graphics.gapi.ui["\x1b\f\x03"]["\x1b\f\x04"]);
      Object.registerClass("UI_WaypointsItem",dofus.graphics.gapi.ui["\x1b\x18\x18"]["\x1b\x18\x19"]);
      Object.registerClass("ButtonFlatRoundDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("UI_Buff",dofus.graphics.gapi.ui.Buff);
      Object.registerClass("BuffViewer",dofus.graphics.gapi.controls.BuffViewer);
      Object.registerClass("UI_BuffInfos",dofus.graphics.gapi.ui.BuffInfos);
      Object.registerClass("UI_DocumentRoadSignRight",dofus.graphics.gapi.ui.DocumentRoadSign);
      Object.registerClass("UI_DocumentRoadSignLeft",dofus.graphics.gapi.ui.DocumentRoadSign);
      Object.registerClass("SpecializationViewer",dofus.graphics.gapi.controls["\x16\x03\x01"].SpecializationViewer);
      Object.registerClass("RankViewer",dofus.graphics.gapi.controls["\x16\x03\x01"].RankViewer);
      Object.registerClass("AlignmentViewerOrder",dofus.graphics.gapi.controls["\x16\x03\x01"].AlignmentViewerOrder);
      Object.registerClass("AlignmentViewerTree",dofus.graphics.gapi.controls["\x16\x03\x01"].AlignmentViewerTree);
      Object.registerClass("AlignmentViewerFeatsItem",dofus.graphics.gapi.controls["\x16\x03\x01"].AlignmentViewerFeatsItem);
      Object.registerClass("UI_FightsInfos",dofus.graphics.gapi.ui.FightsInfos);
      Object.registerClass("UI_FightsInfosPlayerItem",dofus.graphics.gapi.ui["\x17\x0f\x1c"]["\x17\x10\x01"]);
      Object.registerClass("UI_FightsInfosFightItem",dofus.graphics.gapi.ui["\x17\x0f\x1c"]["\x17\x0f\x1d"]);
      Object.registerClass("UI_Tips",dofus.graphics.gapi.ui.Tips);
      Object.registerClass("UI_CardsCollection",dofus.graphics.gapi.ui.CardsCollection);
      Object.registerClass("Card",dofus.graphics.gapi.controls.Card);
      Object.registerClass("CardFamily",dofus.graphics.gapi.controls.CardFamily);
      Object.registerClass("MonsterListItem",dofus.graphics.gapi.controls.MonsterListItem);
      Object.registerClass("UI_Indicator",dofus.graphics.gapi.ui.Indicator);
      Object.registerClass("UI_ServersManagerRetry",dofus.graphics.gapi.ui.ServersManagerRetry);
      Object.registerClass("UI_Shortcuts",dofus.graphics.gapi.ui.Shortcuts);
      Object.registerClass("UI_Debug",dofus.graphics.gapi.ui.Debug);
      Object.registerClass("UI_Quests",dofus.graphics.gapi.ui.Quests);
      Object.registerClass("UI_PartyItem",dofus.graphics.gapi.ui["\x1a\x04\x03"]["\x1a\x04\x04"]);
      Object.registerClass("UI_Party",dofus.graphics.gapi.ui.Party);
      Object.registerClass("UI_MountStorage",dofus.graphics.gapi.ui.MountStorage);
      Object.registerClass("UI_BigStoreSell",dofus.graphics.gapi.ui.BigStoreSell);
      Object.registerClass("UI_BigStoreBuyPricesGrid",dofus.graphics.gapi.ui.bigstore.BigStorePricesGrid);
      Object.registerClass("UI_BigStoreSellPricesGrid",dofus.graphics.gapi.ui.bigstore.BigStorePricesGrid);
      Object.registerClass("UI_BigStoreSell",dofus.graphics.gapi.ui.BigStoreSell);
      Object.registerClass("UI_CrafterList",dofus.graphics.gapi.ui.CrafterList);
      Object.registerClass("UI_BigStoreBuy",dofus.graphics.gapi.ui.BigStoreBuy);
      Object.registerClass("UI_BigStoreBuy_TripleFramerate",dofus.graphics.gapi.ui.BigStoreBuy);
      Object.registerClass("UI_CardsUpgrader",dofus.graphics.gapi.ui.CardsUpgrader);
      Object.registerClass("UI_CardsUpgrader_TripleFramerate",dofus.graphics.gapi.ui.CardsUpgrader);
      Object.registerClass("UI_CustomSet",dofus.graphics.gapi.ui.customset.CustomSet);
      Object.registerClass("UI_CustomSetEdit",dofus.graphics.gapi.ui.customset.CustomSetEdit);
      Object.registerClass("UI_CardsRecycler",dofus.graphics.gapi.ui.CardsRecycler);
      Object.registerClass("UI_BigStoreSearch",dofus.graphics.gapi.ui.BigStoreSearch);
      Object.registerClass("UI_InventorySearch",dofus.graphics.gapi.ui.InventorySearch);
      Object.registerClass("UI_QuestsObjectivetItem",dofus.graphics.gapi.ui["\x1a\t\x02"]["\x1a\t\x03"]);
      Object.registerClass("UI_QuestsStepItem",dofus.graphics.gapi.ui["\x1a\t\x02"]["\x1a\t\x05"]);
      Object.registerClass("UI_QuestsQuestItem",dofus.graphics.gapi.ui["\x1a\t\x02"]["\x1a\t\x04"]);
      Object.registerClass("QuestStepViewer",dofus.graphics.gapi.controls.QuestStepViewer);
      Object.registerClass("QuestStepListViewer",dofus.graphics.gapi.controls.QuestStepListViewer);
      Object.registerClass("UI_PayZoneDialog",dofus.graphics.gapi.ui.PayZoneDialog);
      Object.registerClass("UI_PayZoneDialog2",dofus.graphics.gapi.ui.PayZoneDialog2);
      Object.registerClass("UI_PayZone",dofus.graphics.gapi.ui.PayZone);
      Object.registerClass("UI_PayZone_TripleFramerate",dofus.graphics.gapi.ui.PayZone);
      Object.registerClass("UI_MovableContainerBar",dofus.graphics.gapi.ui.MovableContainerBar);
      Object.registerClass("ButtonSubscribeUp",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("ButtonSubscribeDown",ank.gapi.controls["\x16\x14\x0f"]["\x16\x14\x10"]);
      Object.registerClass("UI_LoginNewsItem",dofus.graphics.gapi.ui.login["\x18\x17\x0f"]);
      Object.registerClass("UI_GiftsSprite",dofus.graphics.gapi.ui.gifts["\x18\x02\x1b"]);
      Object.registerClass("GAPIMain",dofus.graphics.gapi["\x17\x13\n"]);
      Object.registerClass("BATTLEFIELD",dofus.graphics.battlefield["\x17\t\x0b"]);
      Object.registerClass("ToolTip",ank.gapi.controls.ToolTip);
      Object.registerClass("ScrollBarThumb",ank.gapi.controls["\x1a\x11\r"]["\x1a\x11\x14"]);
      Object.registerClass("ScrollBar",ank.gapi.controls.ScrollBar);
      Object.registerClass("PopupMenu",ank.gapi.controls.PopupMenu);
      Object.registerClass("Fps",ank.gapi.controls.Fps);
      Object.registerClass("ConsoleLogger",ank.gapi.controls.ConsoleLogger);
      Object.registerClass("Compass",ank.gapi.controls.Compass);
      Object.registerClass("Clock",ank.gapi.controls.Clock);
      Object.registerClass("MiniMap",dofus.graphics.gapi.controls.MiniMap);
      Object.registerClass("SpriteViewer",dofus.graphics.gapi.controls.SpriteViewer);
      Object.registerClass("UI_AutomaticServer",dofus.graphics.gapi.ui.AutomaticServer);
      Object.registerClass("UI_AutomaticServer_TripleFramerate",dofus.graphics.gapi.ui.AutomaticServer);
      Object.registerClass("UI_ServerInformations",dofus.graphics.gapi.ui.ServerInformations);
      Object.registerClass("UI_TitleDisplayer",dofus.graphics.gapi.ui.TitleDisplayer);
      Object.registerClass("UI_ForgemagusCraft",dofus.graphics.gapi.ui.ForgemagusCraft);
      Object.registerClass("UI_KnownledgeBase",dofus.graphics.gapi.ui.KnownledgeBase);
      Object.registerClass("UI_KnownledgeBaseCategory",dofus.graphics.gapi.ui["\x18\x12\x06"]["\x18\x12\x07"]);
      Object.registerClass("UI_KnownledgeBaseItem",dofus.graphics.gapi.ui["\x18\x12\x06"]["\x18\x12\b"]);
      Object.registerClass("Helper",dofus.graphics.gapi.controls.Helper);
      Object.registerClass("Helper_TripleFramerate",dofus.graphics.gapi.controls.Helper);
      Object.registerClass("UI_FloatingTips",dofus.graphics.gapi.ui.FloatingTips);
      Object.registerClass("MouseShortcuts",dofus.graphics.gapi.controls.MouseShortcuts);
      Object.registerClass("ColorSelector",dofus.graphics.gapi.controls.ColorSelector);
      Object.registerClass("UI_SpellViewerOnCreate",dofus.graphics.gapi.ui.SpellViewerOnCreate);
      Object.registerClass("UI_HistoryViewerOnCreate",dofus.graphics.gapi.ui.HistoryViewerOnCreate);
      Object.registerClass("ClassSelector",dofus.graphics.gapi.controls.ClassSelector);
      Object.registerClass("UI_GuildHouseRights",dofus.graphics.gapi.ui.GuildHouseRights);
      Object.registerClass("GuildHousesViewer",dofus.graphics.gapi.controls.GuildHousesViewer);
      Object.registerClass("GuildHousesViewerHouses",dofus.graphics.gapi.controls["\x18\x04\x03"].GuildHousesViewerHouses);
      Object.registerClass("UI_ItemSummoner",dofus.graphics.gapi.ui.ItemSummoner);
      Object.registerClass("UI_AskReportMessage",dofus.graphics.gapi.ui.AskReportMessage);
      Object.registerClass("UI_Conquest",dofus.graphics.gapi.ui.Conquest);
      Object.registerClass("ConquestStatsViewer",dofus.graphics.gapi.controls.ConquestStatsViewer);
      Object.registerClass("ConquestZonesViewer",dofus.graphics.gapi.controls.ConquestZonesViewer);
      Object.registerClass("ConquestJoinViewer",dofus.graphics.gapi.controls.ConquestJoinViewer);
      Object.registerClass("UI_SpellForget",dofus.graphics.gapi.ui.SpellForget);
      Object.registerClass("UI_SpellForgetItem",dofus.graphics.gapi.ui["\x1b\x06\b"]["\x1b\x06\n"]);
      Object.registerClass("UI_ItemFound",dofus.graphics.gapi.ui.ItemFound);
      Object.registerClass("UI_ChooseFeed",dofus.graphics.gapi.ui.ChooseFeed);
      Object.registerClass("ConquestStatsViewerItem",dofus.graphics.gapi.controls["\x16\x1e\x12"].ConquestStatsViewerItem);
      Object.registerClass("StarsDisplayer",dofus.graphics.gapi.controls.StarsDisplayer);
      Object.registerClass("ConquestZonesViewerAreaItem",dofus.graphics.gapi.controls["\x16\x1e\x16"].ConquestZonesViewerAreaItem);
      Object.registerClass("ConquestZonesViewerVillageItem",dofus.graphics.gapi.controls["\x16\x1e\x16"].ConquestZonesViewerVillageItem);
      Object.registerClass("EffectIcon",dofus.graphics.battlefield.EffectIcon);
      Object.registerClass("SpellFullIcon",dofus.graphics.battlefield.SpellFullIcon);
      Object.registerClass("SpriteHealthBar",dofus.graphics.gapi.controls.SpriteHealthBar);
      Object.registerClass("UI_Survey",dofus.graphics.gapi.ui.Survey);
      Object.registerClass("UI_SurveyNotification",dofus.graphics.gapi.ui.SurveyNotification);
      Object.registerClass("UI_SurveyQuestionItem",dofus.graphics.gapi.ui.SurveyQuestionItem);
   }
}
